#version 430 core

layout(local_size_x = 16, local_size_y = 16) in;

layout(binding = 0) uniform writeonly image2D outputImage;

uniform int width = 1;
uniform int height = 1;
uniform sampler2D inputImage;

float getTan(float fx, vec2 xuv, vec2 nxny) {
	vec2 yuv = nxny / vec2(width - 1, height - 1);
	float fy = texture(inputImage, yuv).r;

	return max(0., length(xuv - yuv) / (fy - fx));
}

void main() {

	// Filter collapsed textures
	if (width < 2 || height < 2) {
		return;
	}

	int x = int(gl_GlobalInvocationID.x);
	int y = int(gl_GlobalInvocationID.y);

	vec2 xuv = vec2(float(x) / float(width - 1), float(y) / float(height - 1));
	float fx = texture(inputImage, xuv).r;

	float minTan = 1.;		// deg. 45

	// Expand outward layer by layer
	for (int r = 1; r < max(width, height); ++r) {
		float tn = -1.;

		// Break if there is no smaller tangen
		if (length(xuv - (vec2(x, y + r) / vec2(width - 1, height - 1))) / (1 - fx) > minTan) {		// smallest possible tangent is greater than minTan
			break;
		}

		// Top side (left to right)
		for (int i = -r; i <= r; ++i) {
			int nx = x + i;
			int ny = y - r;
			if (nx >= 0 && nx < width && ny >= 0 && ny < height) {
				tn = getTan(fx, xuv, vec2(nx, ny));
				if (tn > 0) {
					minTan = min(minTan, tn);
				}
			}
		}

		// Right side (top to bottom)
		for (int i = -r + 1; i <= r; ++i) {
			int nx = x + r;
			int ny = y + i;
			if (nx >= 0 && nx < width && ny >= 0 && ny < height) {
				tn = getTan(fx, xuv, vec2(nx, ny));
				if (tn > 0) {
					minTan = min(minTan, tn);
				}
			}
		}

		// Bottom side (right to left)
		for (int i = r - 1; i >= -r; --i) {
			int nx = x + i;
			int ny = y + r;
			if (nx >= 0 && nx < width && ny >= 0 && ny < height) {
				tn = getTan(fx, xuv, vec2(nx, ny));
				if (tn > 0) {
					minTan = min(minTan, tn);
				}
			}
		}

		// Left side (bottom to top)
		for (int i = r - 1; i >= -r + 1; --i) {
			int nx = x - r, ny = y + i;
			if (nx >= 0 && nx < width && ny >= 0 && ny < height) {
				tn = getTan(fx, xuv, vec2(nx, ny));
				if (tn > 0) {
					minTan = min(minTan, tn);
				}
			}
		}

		// No more fields found in the matrix
		if (tn < 0) {
			break;
		}
	}

	imageStore(outputImage, ivec2(gl_GlobalInvocationID), vec4(fx, minTan, 0, 1.));
    
}