#version 430 core

layout(local_size_x = 16, local_size_y = 16) in;

layout(binding = 0) uniform writeonly image2D outputImage;

uniform int width = 1;
uniform int height = 1;
uniform sampler2D inputImage;

/*
void main() {

	// Texture is 1x1 in size
	if (width < 2 && height < 2) {
		imageStore(outputImage, ivec2(0, 0), vec4(texture(inputImage, vec2(0,0)).r, 0, 0, 1.));
	}

	uint x = gl_GlobalInvocationID.x;
	uint y = gl_GlobalInvocationID.y;

	vec2 xuv = vec2(
		width < 2 ? 0.0 : float(x) / float(width - 1),
		height < 2 ? 0.0 : float(y) / float(height - 1)
	);
	float fx = texture(inputImage, xuv).r;

	float maxCos = 0.;

    for (int i = 0; i < width; ++i) {
		for (int j = 0; j < height; ++j) {

			if (i == x && j == y) {
				continue;
			}

			vec2 yuv = vec2(
				width < 2 ? 0.0 : float(i) / float(width - 1),
				height < 2 ? 0.0 : float(j) / float(height - 1)
			);
			float fy = texture(inputImage, yuv).r;

			float a = length(yuv - xuv);
			float b = fy - fx;
			float c = sqrt(a * a + b * b);

			float cosa = b / c;
			maxCos = max(maxCos, cosa);

			// maxm = length(xuv - vec2(0));

		}
	}

	imageStore(outputImage, ivec2(gl_GlobalInvocationID), vec4(fx, maxCos, 0, 1.));
	// imageStore(outputImage, ivec2(gl_GlobalInvocationID), vec4(.5, 0, 0, 1.));
    
}
*/

void main() {

	uint x = gl_GlobalInvocationID.x;
	uint y = gl_GlobalInvocationID.y;

	// vec2 xuv = vec2(float(x) / float(width), float(y) / float(height));
	vec2 xuv = vec2(
		width < 2 ? 0.0 : float(x) / float(width - 1),
		height < 2 ? 0.0 : float(y) / float(height - 1)
	);
	float fx = texture(inputImage, xuv).r;

	// float maxm = 0.;
	float minTan = 1.;

    for (int i = 0; i <= width; ++i) {
		for (int j = 0; j <= height; ++j) {

			if (i == x && j == y) {
				continue;
			}

			// vec2 yuv = vec2(float(i) / float(width), float(j) / float(height));
			vec2 yuv = vec2(
				width < 2 ? 0.0 : float(i) / float(width - 1),
				height < 2 ? 0.0 : float(j) / float(height - 1)
			);
			float fy = texture(inputImage, yuv).r;

			// float m = abs(fy - fx) / length(xuv - yuv);

			float t = length(xuv - yuv) / (fy - fx);
			// float t = length(vec2(x,y) - vec2(i,j)) / abs(fy - fx);

			// maxm = max(maxm, m);
			if (t>0)
			minTan = min(minTan, t);

			// maxm = length(xuv - vec2(0));

		}
	}

	minTan = max(minTan, 0);
	imageStore(outputImage, ivec2(gl_GlobalInvocationID), vec4(fx, minTan, 0, 1.));
	// imageStore(outputImage, ivec2(gl_GlobalInvocationID), vec4(.5, 0, 0, 1.));
    
}